version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
        - app_network
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    networks:
      - app_network
    #[INFO]: The port is exposed to the host machine to allow development with no docker app
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123@Change
      POSTGRES_DB: equipment_tracking

networks:
  app_network:
    driver: bridge

volumes:
  data:
